### ISSUE TITLE
UITextView inside UICollectionView not scrolling when using StackTransformView

### ISSUE THREAD

**Issue by nanovationlabs** [amirdew/CollectionViewPagingLayout#15]
Alright this is a bit weird let me see if I can explain it well enough. I think it is fairly easy to replicate also.

Basically when using the `StackTransformView` if you have a UITextView that is suppoused to scroll then it won't detect the touch on the second cell and onwards and you won't be able to scroll.

Looking at it more closer I decided to check the example.

I decided to add the event to detect when a cell is selected in `ShapesViewController` like this:

```
func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        if collectionView == self.collectionView {
            print("Clicked cell at")
            print(indexPath)
        }
}
```

Now when trying the `ScaleTransformView` examples or `SnapshotTransformView` when you tap on the second cell the output will in console will be `Clicked cell at [0, 1]` if you tap the third then it should be `Clicked cell at [0, 2]`.

But when doing the same with `StackTransformView` the output is always the same `Clicked cell at [0, 0]`.

It seems as if the animation to change cell is done and the contentview of the cell is moved and animated but the first cell is always in the front capturing the touches.

Another way to see this is by replacing the `ImageView` in the `ShapeCardView.xib` stackView for a `TextView`. Because the first cell seems to be always in the front capturing the touches you won't be able to scroll text on the second or third cell and so on.

It is kind of weird and I tried to look into it but have no idea what is going on.

Surprisingly if we apply our own transform into `TransformableView` like it is done on the credit card example in  `CardCollectionViewCell` this problem is not there and touches go to their respective cells and scrolling is possible in the text view.

**Comment by nanovationlabs** [comment]
After playing a bit more around with it I think the problem comes from the `func zPosition(progress: CGFloat) -> Int` in `StackTransformView`.

If I ignore the option `stackOptions.reverse` , comment everything and in this method just return the default `return Int(-abs(round(progress)))` scrolling works perfectly on the textview inside the collection view cells. But when doing this the reverse breaks so I can only use normal configuration that do not need the reverse option being true.

Same happens if I decide to override the zPosition method with an extension on the collectionviewcell class.

Hopefully this helps.

**Comment by amirdew** [comment]
Hi, thanks for adding this issue.   
I think your right when `stackOptions.reverse` is true, zPosition should be calculated differently,
I'll come back to this in a couple of days

**Comment by amirdew** [comment]
Okay, I needed to explain this in the `limitations` section but I didn't, my bad.
the way that this layout works is putting all the cells in the collectionview bounds (doesn't matter which TransformView you use)
and then it applies transforms on the target view (`StackTransformView.cardView`, `ScaleTransformView.scalableView` etc)
so basically you cannot use `func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath)`
because all cells always are on top of each other and the first visible cell is always on the top that's why you always get [0, 0]
this is a downside however it gives you more flexibility to work with the view like using auto layout and more.
now there is a simple solution for selecting cells and that is adding a tap gesture to the view inside your cell! (I added more info at the end of this comment).

If you want to handle touch gestures for multiple cells at the same time you need to somehow disable touch on your `cell.contentview` and then it passes the touch gesture to the next view which is your next cell.
I haven't tested that because I didn't need it but I think it's doable.
If you don't need to handle touch gestures on multiple cells at the same time you can always override `func zPosition(progress: CGFloat) -> Int` in you cell and return a higher number for the cell that you want to be responsible for touch gestures.


for handling `select at indexPath` you can use the future version branch, 
you need to specify the branch in your podfile:
```swift
pod 'CollectionViewPagingLayout', :git => 'https://github.com/amirdew/CollectionViewPagingLayout.git', :branch => 'macApp'
``` 
you just need to set a delegate for the layout and call a method(`configureTapOnCollectionView(goToSelectedPage:)`).
then you get a similar method for selecting the cell:

```swift

class YourViewController {
    func setupCollectionView() {
        let layout = CollectionViewPagingLayout()
        layout.delegate = self
        collectionView.collectionViewLayout = layout
        layout.configureTapOnCollectionView(goToSelectedPage: true)
    }
}

extension YourViewController: CollectionViewPagingLayoutDelegate {
    func collectionViewPagingLayout(_ layout: CollectionViewPagingLayout, didSelectItemAt indexPath: IndexPath) {
        print(indexPath)
    }
}
```

**Comment by amirdew** [comment]
I added a bullet point and explained the limitation with touches         
I close this issue but feel free to reopen it if you have any question
